import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex">
        <nav className="flex flex-col h-screen bg-indigo-800 text-white px-2 w-48 py-2 shrink-0">
          <h1 className="text-xl text-center w-full font-semibold text-indigo-100 mt-1">SideBar</h1>
          <ul className="flex flex-col mt-4">
            <li className="hover:bg-indigo-700 rounded transition ease-in-out">
              <Link href='/dashboard' className="flex px-2 py-1">Dashboard</Link>
            </li>
            <li className="hover:bg-indigo-700 rounded transition ease-in-out">
              <Link href='/dashboard' className="flex px-2 py-1">Todo Link</Link>
            </li>
          </ul>
        </nav>
        <main className="flex-1 mx-8 my-2">
          {children}
        </main>
      </body>
    </html>
  );
}
